/*package lt.codeacademy.baigiamasisDarbasOOP;

public enum Subjects {
    KOMPIUTERIU_ARCHITEKTURA,
    PROCEDURINIS_PROGRAMAVIMAS,
    ALGORITMAI_IR_DUOMENU_STRUKTUROS,
    OBJEKTINIS_PROGRAMAVIMAS,
    VERSLO_PROCESU_MODELIAVIMAS,
    DUOMENU_BAZIU_PROJEKTAVIMAS,
    OPERACINES_SISTEMOS,
    RINKODARA,
    DIRBTINIO_INTELEKTO_PAGRINDAI,
    VADYBOS_PAGRINDAI,
    VERSLO_ANALITIKA,
    INFORMACINIU_SISTEMU_TESTAVIMAS_IR_PRIEZIURA,
    FIZINE_CHEMIJA,
    BENDROJI_BIOLOGIJA,
    BIOCHEMIJA
}*/
