version: '3.5'

services:
  database:
    image: mysql:5.6
    container_name: docker-compose-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myComposeRootPassword
      MYSQL_DATABASE: eshopdb
      MYSQL_USER: composeEshopUser
      MYSQL_PASSWORD: composePassword
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_volume: